export const SAVE_SEARCH_RESULTS = "SAVE_SEARCH_RESULTS";
export const LOADING_START = "LOADING_START";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_FAILED = "LOADING_FAILED";
export const RESET_SEARCH_RESULTS = "RESET_SEARCH_RESULTS";
export const STORE_SEARCH_KEY = "STORE_SEARCH_KEY";