export const SAVE_SEARCH_RESULTS = "SAVE_SEARCH_RESULTS";
export const LOADING_START = "LOADING_START";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_FAILED = "LOADING_FAILED";